### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by meghanmalone** [abhisheksoni27/whatsapp-chat-analysis#1]
With the line 

plt.xticks(range(len(time_groups)), list(time_groups.keys()))
                                                                               
I am receiving SyntaxError: invalid Syntax. Does anyone know why? The upper arrow that shows the error is pointing to the period between groups.keys

**Comment by abhisheksoni27** [comment]
Can you post a screenshot of the exact trace? Also, which version of Python are you using?

**Comment by meghanmalone** [comment]
yes here are the two different errors i am getting
________________________________

**Comment by abhisheksoni27** [comment]
I am sorry, did you forget to attach the trace?

**Comment by meghanmalone** [comment]
Is that the code?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by abhisheksoni27** [comment]
I do not understand what you are saying. I am asking: Can you paste the stack trace (the error output you get in the terminal. ALso, can you tell me which version of Python are you using? 2.7 or 3?)
